=== seongahpark/SSAFY-8th/2022.07.28/src/io/xml/emp-list.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT emp-list (emp*)>
<!ELEMENT emp (emp-id,emp-nm,salary,enter-dt)>
<!ELEMENT emp-id (#PCDATA)>
<!ELEMENT emp-nm (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT enter-dt (#PCDATA)>

=== seongahpark/SSAFY-8th/2022.07.28/src/io/xml/emp-list.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE emp-list SYSTEM "emp-list.dtd">

<emp-list>
    <emp>
        <emp-id>111</emp-id>
        <emp-nm>홍길동</emp-nm>
        <salary>4000</salary>
        <enter-dt>2022-01-31</enter-dt>
    </emp>
    <emp>
        <emp-id>222</emp-id>
        <emp-nm>이길동</emp-nm>
        <salary>5000</salary>
        <enter-dt>2022-11-04</enter-dt>
    </emp>
    <emp>
        <emp-id>333</emp-id>
        <emp-nm>삼길동</emp-nm>
        <salary>6000</salary>
        <enter-dt>2022-02-15</enter-dt>
    </emp>
    <emp>
        <emp-id>444</emp-id>
        <emp-nm>사길동</emp-nm>
        <salary>7000</salary>
        <enter-dt>2022-07-22</enter-dt>
    </emp>
    <emp>
        <emp-id>555</emp-id>
        <emp-nm>오길동</emp-nm>
        <salary>8000</salary>
        <enter-dt>2022-05-11</enter-dt>
    </emp>
</emp-list>
